#!/usr/bin/env node
/**
 * Image optimizer for henna-tattoo-web (Astro + Tailwind)
 *
 * Architecture
 * ------------
 *   _originals/         <- drop full-resolution photos here (gitignored)
 *      jagua/IMG_0010.jpeg
 *      brown.jpg
 *
 *   public/images/      <- AUTO-GENERATED by this script. Do NOT hand-edit.
 *      jagua/
 *        IMG_0010.jpg            (max-size fallback, original filename)
 *        IMG_0010-640.avif       (responsive variants)
 *        IMG_0010-640.webp
 *        IMG_0010-640.jpg
 *        IMG_0010-1024.avif
 *        IMG_0010-1024.webp
 *        IMG_0010-1024.jpg
 *        IMG_0010-1600.avif
 *        IMG_0010-1600.webp
 *        IMG_0010-1600.jpg
 *
 * What it does (per image)
 * ------------------------
 *   1. EXIF auto-rotate, then strip metadata (privacy + smaller files).
 *   2. Detect transparency: PNG with no alpha → JPG.
 *      PNG with alpha   → kept as PNG.
 *   3. Cap each output at MAX_WIDTH (default 1600 px on the long edge —
 *      enough for full-bleed on a Mac retina at 2x DPR).
 *   4. Emit responsive widths: 640 / 1024 / 1600 px (skips widths larger
 *      than the source).
 *   5. For every width, emit AVIF + WebP + JPG/PNG so <picture> can serve
 *      whatever the browser supports best.
 *   6. Also emit the "fallback" file at the original filename + max width,
 *      so existing <img src="/images/foo.jpg"> references keep working.
 *
 * Why these formats (state of the web in 2026)
 * --------------------------------------------
 *   AVIF  — best compression (~50% smaller than JPG at equal quality).
 *           Supported by Chrome/Edge/Firefox/Safari 16+ (~96% global).
 *   WebP  — fallback for older Safari, ~25–35% smaller than JPG. ~98%.
 *   JPG   — universal fallback. mozjpeg encoder for ~10% extra savings.
 *   PNG   — only used when transparency is required (logos, cutouts).
 *
 * Usage
 * -----
 *   npm run images          # optimize everything that changed
 *   npm run images -- --force   # re-optimize all (ignores manifest)
 *   npm run images -- --dry     # show what would happen, write nothing
 */

import { promises as fs } from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import { createHash } from 'node:crypto';
import sharp from 'sharp';

const __dirname = path.dirname(url.fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const SRC_DIR = path.join(ROOT, '_originals');
const OUT_DIR = path.join(ROOT, 'public', 'images');
const MANIFEST_PATH = path.join(__dirname, '.image-manifest.json');

// ---- Tunables ---------------------------------------------------------------
const RESPONSIVE_WIDTHS = [640, 1024, 1600];
const MAX_WIDTH = 1600;             // long-edge cap for the "fallback" file
const AVIF_QUALITY = 55;            // 50–60 is the sweet spot for photos
const WEBP_QUALITY = 80;
const JPG_QUALITY  = 82;            // mozjpeg
const PNG_COMPRESSION = 9;          // max zlib effort, lossless
const SUPPORTED_INPUT = new Set([
  '.jpg', '.jpeg', '.png', '.webp', '.tif', '.tiff', '.heic', '.heif', '.avif',
]);

// ---- CLI flags --------------------------------------------------------------
const args = new Set(process.argv.slice(2));
const FORCE = args.has('--force');
const DRY   = args.has('--dry');

// ---- Helpers ----------------------------------------------------------------
const log = (...m) => console.log(...m);
const fmt = (b) => (b > 1024 * 1024
  ? (b / 1024 / 1024).toFixed(2) + ' MB'
  : (b / 1024).toFixed(1) + ' KB');

async function walk(dir, base = dir) {
  const out = [];
  let entries;
  try {
    entries = await fs.readdir(dir, { withFileTypes: true });
  } catch {
    return out;
  }
  for (const e of entries) {
    if (e.name.startsWith('.')) continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) {
      out.push(...(await walk(full, base)));
    } else {
      out.push({ full, rel: path.relative(base, full) });
    }
  }
  return out;
}

async function loadManifest() {
  try {
    return JSON.parse(await fs.readFile(MANIFEST_PATH, 'utf8'));
  } catch {
    return {};
  }
}

async function saveManifest(m) {
  if (DRY) return;
  await fs.writeFile(MANIFEST_PATH, JSON.stringify(m, null, 2));
}

async function hashKey(filePath) {
  // Content hash so the manifest survives across machines. mtime would
  // reset on every fresh `git clone` (e.g. on Netlify's build VM) and
  // force re-encoding all 128 photos every deploy (~7 min). With sha1
  // of file bytes the optimizer skips unchanged sources in <1s total.
  const buf = await fs.readFile(filePath);
  const s = await fs.stat(filePath);
  const h = createHash('sha1').update(buf).digest('hex').slice(0, 16);
  return `${s.size}:${h}`;
}

function variantPaths(rel) {
  // rel like 'jagua/IMG_0010.jpeg' — preserve the original extension so that
  // existing string references in templates and src/lib/categories.ts keep
  // working without any rewrite. The bandwidth win comes from the AVIF / WebP
  // siblings that <picture> serves to ~95%+ of browsers.
  const ext = path.extname(rel);
  const dir = path.dirname(rel);
  const stem = path.basename(rel, ext);
  const widthVariants = (w) => ({
    avif: path.join(dir, `${stem}-${w}.avif`),
    webp: path.join(dir, `${stem}-${w}.webp`),
    raster: path.join(dir, `${stem}-${w}${ext}`),
  });
  return {
    fallback: rel,
    widths: RESPONSIVE_WIDTHS.map((w) => ({ w, ...widthVariants(w) })),
    fallbackExt: ext,
    rel,
  };
}

async function ensureDir(relPath) {
  if (DRY) return;
  await fs.mkdir(path.dirname(path.join(OUT_DIR, relPath)), { recursive: true });
}

async function writeAvif(pipeline, dest) {
  await ensureDir(dest);
  if (DRY) return 0;
  const info = await pipeline.clone()
    .avif({ quality: AVIF_QUALITY, effort: 4 })
    .toFile(path.join(OUT_DIR, dest));
  return info.size;
}

async function writeWebp(pipeline, dest) {
  await ensureDir(dest);
  if (DRY) return 0;
  const info = await pipeline.clone()
    .webp({ quality: WEBP_QUALITY, effort: 5 })
    .toFile(path.join(OUT_DIR, dest));
  return info.size;
}

async function writeRaster(pipeline, dest) {
  // Encoder is picked from the file extension so the bytes inside the file
  // always match the Content-Type Netlify will serve.
  await ensureDir(dest);
  if (DRY) return 0;
  const p = pipeline.clone();
  const ext = path.extname(dest).toLowerCase();
  const out = path.join(OUT_DIR, dest);
  if (ext === '.png') {
    const info = await p.png({ compressionLevel: PNG_COMPRESSION, palette: true })
                        .toFile(out);
    return info.size;
  }
  // .jpg / .jpeg / anything else photographic
  const info = await p.jpeg({ quality: JPG_QUALITY, mozjpeg: true, progressive: true })
                      .toFile(out);
  return info.size;
}

async function copyThrough(srcAbs, rel) {
  // For SVGs and other files we don't transcode.
  const dest = path.join(OUT_DIR, rel);
  if (DRY) return;
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.copyFile(srcAbs, dest);
}

async function processOne(file, manifest) {
  const ext = path.extname(file.rel).toLowerCase();

  // SVG and other non-raster: copy untouched.
  if (ext === '.svg') {
    await copyThrough(file.full, file.rel);
    const key = await hashKey(file.full);
    manifest[file.rel] = { key, kind: 'copy' };
    return { rel: file.rel, savedBytes: 0, copied: true };
  }

  if (!SUPPORTED_INPUT.has(ext)) {
    log(`  ↷ skip (unsupported): ${file.rel}`);
    return null;
  }

  const key = await hashKey(file.full);
  if (!FORCE && manifest[file.rel]?.key === key) {
    return { rel: file.rel, savedBytes: 0, skipped: true };
  }

  const srcSize = (await fs.stat(file.full)).size;
  const input = sharp(file.full, { failOn: 'none' }).rotate(); // EXIF rotate
  const meta  = await input.metadata();
  const hasAlpha = !!meta.hasAlpha && (meta.channels === 4 || meta.channels === 2);
  const srcW = meta.width  || MAX_WIDTH;

  const paths = variantPaths(file.rel);

  // Master fallback: same path/extension as source, max width capped, EXIF stripped.
  const fallbackPipe = sharp(file.full, { failOn: 'none' })
    .rotate()
    .withMetadata({ exif: {}, icc: undefined })
    .resize({
      width: Math.min(srcW, MAX_WIDTH),
      withoutEnlargement: true,
      fit: 'inside',
    });

  let written = 0;
  written += await writeRaster(fallbackPipe, paths.fallback);

  // Responsive variants — only widths <= source width.
  for (const v of paths.widths) {
    if (v.w > srcW) continue;
    const pipe = sharp(file.full, { failOn: 'none' })
      .rotate()
      .withMetadata({ exif: {}, icc: undefined })
      .resize({ width: v.w, withoutEnlargement: true, fit: 'inside' });
    written += await writeAvif(pipe, v.avif);
    written += await writeWebp(pipe, v.webp);
    written += await writeRaster(pipe, v.raster);
  }

  manifest[file.rel] = {
    key,
    kind: 'image',
    fallback: paths.fallback,
    widths: paths.widths.filter((v) => v.w <= srcW).map((v) => v.w),
    hasAlpha,
    extOriginal: ext,
    extFallback: paths.fallbackExt,
  };

  const saved = srcSize - written;
  log(
    `  ✓ ${file.rel}  ${fmt(srcSize)} → ${fmt(written)} ` +
    `(${saved >= 0 ? '-' : '+'}${fmt(Math.abs(saved))})`,
  );
  return { rel: file.rel, savedBytes: saved };
}

async function pruneStale(manifest) {
  // Remove files in public/images/ that no longer correspond to anything in
  // _originals/. This keeps things tidy when a source image is deleted.
  const all = await walk(OUT_DIR);
  const knownKeep = new Set();
  for (const [rel, entry] of Object.entries(manifest)) {
    if (entry.kind === 'copy') {
      knownKeep.add(rel);
      continue;
    }
    knownKeep.add(entry.fallback);
    const stem = path.basename(rel, path.extname(rel));
    const dir  = path.dirname(rel);
    for (const w of entry.widths) {
      knownKeep.add(path.join(dir, `${stem}-${w}.avif`));
      knownKeep.add(path.join(dir, `${stem}-${w}.webp`));
      knownKeep.add(path.join(dir, `${stem}-${w}${entry.extFallback}`));
    }
  }
  let removed = 0;
  for (const f of all) {
    if (!knownKeep.has(f.rel)) {
      if (!DRY) await fs.unlink(f.full);
      removed += 1;
      log(`  ✗ removed stale: ${f.rel}`);
    }
  }
  return removed;
}

async function main() {
  log('▸ Image optimizer');
  log(`  src: ${path.relative(ROOT, SRC_DIR)}/`);
  log(`  out: ${path.relative(ROOT, OUT_DIR)}/`);
  if (FORCE) log('  mode: --force (re-encode everything)');
  if (DRY)   log('  mode: --dry (no files will be written)');

  const srcExists = await fs.stat(SRC_DIR).then(() => true).catch(() => false);
  if (!srcExists) {
    console.error(
      `\n_originals/ not found at ${SRC_DIR}.\n` +
      `Create it and drop your full-resolution photos in there.`,
    );
    process.exit(1);
  }

  const files = await walk(SRC_DIR);
  if (files.length === 0) {
    log('  (no source images found)');
    return;
  }
  log(`  found ${files.length} source files\n`);

  const manifest = await loadManifest();
  let totalSaved = 0;
  let processed = 0;
  let skipped = 0;

  for (const file of files) {
    const result = await processOne(file, manifest);
    if (!result) continue;
    if (result.skipped) { skipped += 1; continue; }
    if (!result.copied)  totalSaved += result.savedBytes;
    processed += 1;
  }

  // Drop manifest entries for source files that no longer exist.
  const liveSet = new Set(files.map((f) => f.rel));
  for (const k of Object.keys(manifest)) {
    if (!liveSet.has(k)) delete manifest[k];
  }

  const removed = await pruneStale(manifest);

  await saveManifest(manifest);

  log('');
  log(`▸ Done. processed=${processed}  skipped(unchanged)=${skipped}  pruned=${removed}`);
  log(`  bytes saved on processed files: ${fmt(Math.max(totalSaved, 0))}`);
  if (DRY) log('  (dry run — no files written)');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
